# Generated by Django 3.0.3 on 2020-08-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
