# Generated by Django 3.0.3 on 2020-09-03 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0004_auto_20200831_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='blogpost',
            new_name='blogpost_connected',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='date_added',
            new_name='date_posted',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
